let currentMotivoIndex = 0;

document.getElementById('revealButton').addEventListener('click', function() {
	
const motivos = [
"1 - Eu amo o seu olhar",
"2 - Eu amo sua voz",
"3 - Eu amo o seu sorriso",
"4 - Eu amo o seu cheiro (não senti mas amo)",
"5 - Eu amo o seu carinho",
"6 - Eu amo o seu nariz",
"7 - Eu amo o seu olho",
"8 - Eu amo sua risada",
"9 - Eu amo ter você na minha vida",
"10 - Eu amo o seu cabelo",
"11 - Eu amo o seu jeito de falar egua",
"12 - Eu amo a sua criatividade",
"13 - Eu amo o cuidado que você tem comigo",
"14 - Eu amo como você me chama de Gabriel",
"15 - Eu amo acordar com seu bom dia",
"16 - Eu amo a sua carinha",
"17 - Eu amo o seu romantismo",
"18 - Eu amo conversar com você",
"19 - Eu amo como você me faz ser romântico",
"20 - Eu amo o seu bico",
"21 - Eu amo as suas birras",
"22 - Eu amo como você se entrega",
"23 - Eu amo sua boca",
"24 - Eu amo nossas conversas",
"25 - Eu amo como você trata o Miguel",
"26 - Eu amo seu corpo",
"27 - Eu amo quando me manta foto do seu cabelo",
"28 - Eu amo quando você se arruma",
"29 - Eu amo a sua inteligência",
"30 - Eu amo quando você fica tímida",
"31 - Eu amo como você me entende",
"32 - Eu amo suas costas",
"33 - Eu amo suas coxas",
"34 - Eu amo o seu corpo",
"35 - Eu amo dormir falando com você",
"36 - Eu amo quando você fala xiim",
"37 - Eu amo cuidar de você",
"38 - Eu amo te mimar",
"39 - Eu amo te dar carinho",
"40 - Eu amo te proteger",
"41 - Eu amo nossos planos sobre o futuro",
"42 - Eu amo a Ísis.",
"43 - Eu amo quando você fala “mô”",
"44 - Eu amo o Miguel",
"45 - Eu amo como a gente consegue se resolver",
"46 - Eu amo quando você fica bravinha",
"47 - Eu amo cada detalhe seu",
"48 - Eu amo a forma como você me conhece tão bem.",
"49 - Eu amo te admirar",
"50 - Eu amo a forma como você me faz sonhar.",
"51 - Eu amo a forma como você me faz sentir amado",
"52 - Eu amo mandar em ti (KKKKKKK)",
"53 - Eu amo quando você fica dengosa",
"54 - Eu amo seu sorrisinho",
"55 - Eu amo a força com que te amo, mesmo a distância",
"56 - Eu amo planejar as coisas com você",
"57 - Eu amo como somos bestas juntos",
"58 - Eu amo planejar o futuro com você",
"59 - Eu amo os seus áudios",
"60 - Eu amo sonhar com você",
"61 - Eu amo quando você sonha comigo",
"62 - Eu amo suas manias",
"63 - Eu amo quando você se entrega para mim",
"64 - Eu amo te amar",
"65 - Eu amo te chamar de vida",
"66 - Eu amo sentir tesão por você",
"67 - Eu amo ser louco por você",
"68 - Eu amo sonhar com você",
"69 - Eu amo sentir sua falta",
"70 - Eu amo que você seja minha paz",
"71 - Eu amo como conversamos sobre tudo",
"72 - Eu amo como você é apaixonante",
"73 - Eu amo como você é brilhante",
"74 - Eu amo como você é uma princesinha",
"75 - Eu amo o quanto você é uma mulher incrível",
"76 - Eu amo como você fez eu perder o medo de amar de novo",
"77 - Eu amo como você é minha melhor amiga",
"78 - Eu amo os seus estilos",
"79 - Eu amo quando você diz que me ama",
"80 - Eu amo reparar nos seus detalhes",
"81 - Eu amo reparar o seu jeito",
"82 - Eu amo como seu olho brilha",
"83 - Eu amo quando estou com você o tempo passa rápido",
"84 - Eu amo quando estou com você o tempo passa devagar",
"85 - Eu amo suas bobagens",
"86 - Eu amo como você me faz rir",
"87 - Eu amo como você faz eu me sentir diferente do que já fui um dia",
"88 - Eu amo saber que vou me casar com você",
"89 - Eu amo ser seu",
"90 - Eu amo que você é minha",
"91 - Eu amo a sua voz",
"92 - Eu amo a suas fofocas",
"93 - Eu amo ver filme com você",
"94 - Eu amo quando você me chama de Marcos só pra me irritar",
"95 - Eu amo como você se importa com o meu sucesso e a minha felicidade.",
"96 - Eu amo te irritar",
"97 - Eu amo acordar de madrugada e ter mensagem sua",
"98 - Eu amo te chamar de minha",
"99 - Eu amo a sua persistência",
"100 - Eu amo a sua teimosia",
"101 - Eu amo como você dá esperança para minha vida.",
"102 - Eu amo sua mão",
"103 - Eu amo o seu pé",
"104 - Eu amo suas unhas",
"105 - Eu amo o seu sorriso após eu ser fofo",
"106 - Eu amo a cor dos seus olhos",
"107 - Eu amo que você cruzou o meu caminho quando eu mais precisava",
"108 - Eu amo quando você fala empolgada sobre um assunto que você gosta",
"109 - Eu amo quando você pensa em mim",
"110 - Eu amo como você me deixa apaixonado",
"111 - Eu amo como você me traz paz",
"112 - Eu amo seu sotaque Macapaense",
"113 - Eu amo como você repara em detalhes",
"114 - Eu amo ser seu namorado",
"115 - Eu amo te fazer feliz",
"116 - Eu amo te ver feliz",
"117 - Eu amo como você me mima",
"118 - Eu amo como você é gostosa",
"119 - Eu amo quando você se arruma e me manda foto",
"120 - Eu amo seu jeito",
"121 - Eu amo como você me conhece mais do que eu mesmo",
"122 - Eu amo suas ideias",
"123 - Eu amo sua opinião",
"124 - Eu amo suas piadinhas",
"125 - Eu amo ser obcecado por ti",
"126 - Eu amo o jeito que você me trata",
"127 - Eu amo falar de ti para as pessoas",
"128 - Eu amo o dia 18/03",
"129 - Eu amo ser seu",
"130 - Eu amo sua carinha",
"131 - Eu amo ficar bobinho por você",
"132 - Eu amo quando você me chama de gostoso",
"133 - Eu amo quando posso fazer algo por você",
"134 - Eu amo te admirar em cada foto",
"135 - Eu amo como você me faz bem",
"136 - Eu amo nossos momentos",
"137 - Eu amo nossas lembranças",
"138 - Eu amo mandar fotos de você",
"139 - Eu amo suas fotos",
"140 - Eu amo como somos lindos juntos",
"141 - Eu amo ser fofo contigo",
"142 - Eu amo como você se preocupa comigo",
"143 - Eu amo me preocupar com você",
"144 - Eu amo te dar amor",
"145 - Eu amo você com a camisa do Palmeiras",
"146 - Eu amo ter importância na sua vida",
"147 - Eu amo você ser importante para mim",
"148 - Eu amo ser importante para você",
"149 - Eu amo falar mal das pessoas junto com você",
"150 - Eu amo fofocar com você",
"151 - Eu amo te querer",
"152 - Eu amo sentir sua falta",
"153 - Eu amo como minha necessidade de você aumenta a cada dia",
"154 - Eu amo fazer as coisas que me pede",
"155 - Eu amo como com você eu me sinto capaz de qualquer coisa",
"156 - Eu amo você por ser você",
"157 - Eu amo os seus “defeitos”.",
"158 - Eu amo como você faz o meu coração sorrir",
"159 - Eu amo sua boca",
"160 - Eu amo ser seu grudinho",
"161 - Eu amo ligar pra você",
"162 - Eu amo quando você me chama de chato",
"163 - Eu amo te chamar de chata",
"164 - Eu amo como você me trata bem",
"165 - Eu amo a sua gentileza",
"166 - Eu amo como você me faz ser uma pessoa melhor",
"167 - Eu amo como você me incentiva",
"168 - Eu amo como você me apoia",
"169 - Eu amo como você é dedicada",
"170 - Eu amo como seus conselhos me confortam",
"171 - Eu amo como estamos conectados",
"172 - Eu amo sua fé",
"173 - Eu amo como você é meu porto seguro",
"174 - Eu amo como você atura as minhas bobagens",
"175 - Eu amo acordar com seu bom dia",
"176 - Eu amo quando você se arruma e me manda foto",
"177 - Eu amo como você me completa",
"178 - Eu amo como você coloca cor na minha vida",
"179 - Eu amo que você é a minha maior certeza",
"180 - Eu amo te fazer segura",
"181 - Eu amo te fazer acolhida",
"182 - Eu amo quando você posta Best Part",
"183 - Eu amo que você seja uma pessoa responsável",
"184 - Eu amo quando você sonha alto",
"185 - Eu amo como você cuida de mim quando a ansiedade bate",
"186 - Eu amo quando você me marca em videos",
"187 - Eu amo quando você me lembra quem eu sou",
"188 - Eu amo nossas conversas",
"189 - Eu amo o quanto você se dedica no nosso relacionamento",
"190 - Eu amo o quanto você é uma mãe incrível para o Miguel",
"191 - Eu amo o quanto você é uma ótima filha para a sua mãe",
"192 - Eu amo evoluir com você",
"193 - Eu amo ver nosso amor crescer todos os dias",
"194 - Eu amo saber que temos um amor leve",
"195 - Eu amo saber que você é honesta comigo",
"196 - Eu amo como mudei por você",
"197 - Eu amo como somos incríveis juntos",
"198 - Eu amo como somos fortes juntos",
"199 - Eu amo como você é pequena",
"200 - Eu amo ser flamenguista (mentira)",
"201 - Eu amo o Deyverson",
"202 - Eu amo saber que somos um time",
"203 - Eu amo estar aqui para tudo que você precisar",
"204 - Eu amo pedir sua opinião",
"205 - Eu amo pedir sua ajuda quando eu preciso",
"206 - Eu amo os sorrisos que você me causa",
"207 - Eu amo quando temos metas juntos",
"208 - Eu amo quando você me desafia",
"209 - Eu amo o seu sorriso quando eu te chamo de minha",
"210 - Eu amo o seu sorriso quando eu te chamo de princesa",
"211 - Eu amo o seu sorriso quando eu te chamo de gostosa",
"212 - Eu amo falar égua",
"213 - Eu amo imaginar o nosso futuro",
"214 - Eu amo quando brigamos e fico pensando no seu sorriso e olhar",
"215 - Eu amo como você é romântica",
"216 - Eu amo como você me elogia",
"217 - Eu amo como você presta atenção no que eu falo",
"218 - Eu amo quando fazemos coisas juntos",
"219 - Eu amo quando crescemos juntos",
"220 - Eu amo saber seus gostos",
"221 - Eu amo essa pulseira",
"222 - Eu amo ser romantico contigo",
"223 - Eu amo como você me respeita",
"224 - Eu amo ser paciente com você",
"225 - Eu amo explicar algo que eu gosto para você e você prestar atenção",
"226 - Eu amo a segurança que você me transmite",
"227 - Eu amo a sua preocupação com o Davi",
"228 - Eu amo a forma que você se preocupa com o seu cabelo",
"229 - Eu amo a sua sobrancelha",
"230 - Eu amo como você me acha lindo mesmo todo desleixado",
"231 - Eu amo o nosso relacionamento",
"232 - Eu amo falar que te amo",
"233 - Eu amo nossos assuntos",
"234 - Eu amo que você é tudo que eu preciso",
"235 - Eu amo que você é tudo que eu quero",
"236 - Eu amo como você se veste",
"237 - Eu amo como você é simpática",
"238 - Eu amo a sua bochecha",
"239 - Eu amo a sua barriga",
"240 - Eu amo a sua alegria",
"241 - Eu amo a sua energia",
"242 - Eu amo a sua carência",
"243 - Eu amo como você se faz de desentendida só para eu explicar",
"244 - Eu amo como você me contagia com a sua alegria",
"245 - Eu amo a sua educação",
"246 - Eu amo o seu bom senso",
"247 - Eu amo quando você fala de Macapá",
"248 - Eu amo viajar com você",
"249 - Eu amo o nosso jeito “maduro”",
"250 - Eu amo seu corpo",
"251 - Eu amo seu drama",
"252 - Eu amo como você me serve de exemplo",
"253 - Eu amo que você é a minha mulher",
"254 - Eu amo te chamar de fresca",
"255 - Eu amo que você me aceita como sou.",
"256 - Eu amo como você se destaca",
"257 - Eu amo como eu sou grato por tudo que você faz e fez por mim até hoje",
"258 - Eu amo quando você briga comigo",
"259 - Eu amo seu cíumes",
"260 - Eu amo quando você discorda de mim",
"261 - Eu amo quando você implica com algo",
"262 - Eu amo como você me faz sentir especial",
"263 - Eu amo quando você me faz rir.",
"264 - Eu amo como você fica linda indo pra igreja",
"265 - Eu amo quando você cuida de mim quando estou doente",
"266 - Eu amo como você me apoia em todas as minhas decisões",
"267 - Eu amo quando você diz que sente saudades",
"268 - Eu amo como você me desafia a ser uma pessoa melhor",
"269 - Eu amo como você é minha inspiração",
"270 - Eu amo como você sempre me escuta",
"271 - Eu amo como você se preocupa com o nosso futuro",
"272 - Eu amo como você é carinhosa com os bebês",
"273 - Eu amo como você ilumina qualquer ambiente",
"274 - Eu amo como você me faz querer ser uma pessoa melhor",
"275 - Eu amo quando você diz que me ama",
"276 - Eu amo quando você me faz surpresas",
"277 - Eu amo como você se importa com as pequenas coisas",
"278 - Eu amo como você valoriza cada momento juntos",
"279 - Eu amo como você torna o dia mais bonito só por estar nele",
"280 - Eu amo como você sempre está lá para me apoiar",
"281 - Eu amo como você é otimista",
"282 - Eu amo como você torna a vida mais divertida",
"283 - Eu amo como você consegue ver o lado bom em tudo",
"284 - Eu amo como você é sincera comigo",
"285 - Eu amo quando você me manda mensagens do nada",
"286 - Eu amo como você é minha melhor amiga e namorada ao mesmo tempo",
"287 - Eu amo seus olhos",
"288 - Eu amo como você acredita em mim",
"289 - Eu amo como você faz tudo com amor",
"290 - Eu amo como você me acalma nos momentos difíceis",
"291 - Eu amo como você me surpreende todos os dias",
"292 - Eu amo como você é apaixonada pela vida",
"293 - Eu amo como você me faz sentir vivo",
"294 - Eu amo como você me motiva a seguir meus sonhos",
"295 - Eu amo como você é engraçada sem nem tentar",
"296 - Eu amo como você é curiosa sobre o mundo",
"297 - Eu amo como você se preocupa com a minha saúde",
"298 - Eu amo como você me aceita do jeito que sou",
"299 - Eu amo como você é única",
"300 - Eu amo como você manda foto com efeito engraçado",
"301 - Eu amo como você me faz querer estar sempre perto de você",
"302 - Eu amo como você me faz querer ser o melhor para você",
"303 - Eu amo como você é compreensiva",
"304 - Eu amo como você me faz sentir completo",
"305 - Eu amo como você é a pessoa que eu sempre procurei",
"306 - Eu amo como você me faz acreditar no amor verdadeiro",
"307 - Eu amo como você me faz sentir a pessoa mais sortuda do mundo",
"308 - Eu amo como você ilumina meus dias mais sombrios",
"309 - Eu amo como você me entende sem eu precisar dizer uma palavra",
"310 - Eu amo como você me faz querer planejar nosso futuro",
"311 - Eu amo como você é a minha calmaria no caos",
"312 - Eu amo como você é determinada",
"313 - Eu amo como você é forte",
"314 - Eu amo como você é independente",
"315 - Eu amo como você é minha companheira",
"316 - Eu amo como você me faz sentir amado",
"317 - Eu amo como você é a razão do meu sorriso",
"318 - Eu amo como você transforma pequenos momentos em memórias especiais",
"319 - Eu amo como você é sempre verdadeira",
"320 - Eu amo como você me ensina coisas novas",
"321 - Eu amo como você me faz sentir desejado",
"322 - Eu amo como você me faz esquecer os problemas",
"323 - Eu amo como você me faz querer cuidar de você",
"324 - Eu amo como você é sincera",
"325 - Eu amo como você me faz sentir seguro",
"326 - Eu amo como você é minha confidente",
"327 - Eu amo como você me faz sentir importante",
"328 - Eu amo como você é a luz da minha vida",
"329 - Eu amo como você é a razão do meu bom humor",
"330 - Eu amo como você me faz acreditar em nós",
"331 - Eu amo como você me faz sonhar com um futuro ao seu lado",
"332 - Eu amo como você me faz querer ser melhor todos os dias",
"333 - Eu amo como você me faz sentir disposto",
"334 - Eu amo como você sempre está presente, mesmo quando estamos longe",
"335 - Eu amo como você é o meu porto seguro",
"336 - Eu amo como você me completa",
"337 - Eu amo como você me faz sentir querido",
"338 - Eu amo como você me faz sentir que sou o único no seu mundo",
"339 - Eu amo como você é gentil com todos",
"340 - Eu amo te desejar todos os dias",
"341 - Eu amo como você me faz esquecer o mundo com uma mensagem",
"342 - Eu amo como você sempre me conforta",
"343 - Eu amo como você me faz sentir que posso conquistar qualquer coisa",
"344 - Eu amo como você me faz sentir invencível",
"345 - Eu amo como você me faz sentir que tudo vai ficar bem",
"346 - Eu amo como você é minha cúmplice",
"347 - Eu amo como você é minha parceira em tudo",
"348 - Eu amo como você me faz acreditar que o amor é eterno",
"349 - Eu amo como você me faz sentir sortudo por ter você",
"350 - Eu amo como você me faz querer compartilhar tudo com você",
"351 - Eu amo como você me faz sentir que somos imbatíveis juntos",
"352 - Eu amo como você me faz sentir que sou a pessoa mais especial do mundo",
"353 - Eu amo como você me faz querer ser um homem melhor",
"354 - Eu amo como você me faz sentir amado todos os dias",
"355 - Eu amo como você é a minha princesa",
"356 - Eu amo como você me faz sentir que sou importante na sua vida",
"357 - Eu amo como você me faz acreditar em contos de fadas",
"358 - Eu amo como você me faz querer ser o príncipe do seu conto de fadas",
"359 - Eu amo como você me faz sentir que sou seu para sempre",
"360 - Eu amo como você me faz sentir que somos perfeitos juntos",
"361 - Eu amo como você me faz acreditar no destino",
"362 - Eu amo como você me faz sentir que fomos feitos um para o outro",
"363 - Eu amo como você me faz sentir completo com um simples sorriso",
"364 - Eu amo como você me faz querer passar o resto da minha vida ao seu lado",
"365 - Eu amo cada detalhe seu, cada mania sua, cada momento que estamos juntos e que me fazem ter a certeza de que você é o meu amor!",
,

 ];
    const motivo = motivos[currentMotivoIndex];
    document.getElementById('motivo').textContent = motivo;

    currentMotivoIndex = (currentMotivoIndex + 1) % motivos.length;
	
    // Adicionar corações
    createHearts();
});

function createHearts() {
    const numberOfHearts = 10; // Número de corações para criar
    const container = document.querySelector('.container');

    for (let i = 0; i < numberOfHearts; i++) {
        const heart = document.createElement('div');
        heart.classList.add('heart');
        heart.textContent = '❤️';
        heart.style.left = `${Math.random() * 100}vw`; 
        heart.style.top = `${Math.random() * 100}vh`; 
        heart.style.fontSize = `${Math.random() * 30 + 20}px`; 
        container.appendChild(heart);

        // Remove o coração após a animação
        setTimeout(() => {
            heart.remove();
        }, 5000); // Tempo de duração da animação
    }
}